name: "Continuous Deployment - Build and Push React App Docker Image"

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build_and_push:
    if: github.event.pull_request.merged == true
    name: Build and Push React Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: snippetservices-group4
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/snippetservices-group4/react-app-dev:latest
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
